AllCops:
  TargetRubyVersion: 2.1

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Layout/EndOfLine:
  EnforcedStyle: lf

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
